import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
import typedocSidebar from './docs/api/typedoc-sidebar';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
    // But you can create a sidebar manually
    /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
    // By default, Docusaurus generates a sidebar from the docs folder structure
    tutorialSidebar: [{type: 'autogenerated', dirName: 'tutorial'}],
    // api: [{type: 'autogenerated', dirName: 'api'}],
    apiSidebar: [
        // 1) 文档总览（index.md）
        {
            type: 'doc', // 文档链接项 :contentReference[oaicite:5]{index=5}
            id: 'api/index', // 文档 ID，对应 docs/api/index.md
            label: 'API Overview', // 在 sidebar 中显示的文字
        },
        // 2) 全局类型（globals.md）
        {
            type: 'doc',
            id: 'api/globals', // 对应 docs/api/globals.md
            label: 'Globals',
        },
        {
            type: 'category',
            label: 'Classes',
            link: {
                type: 'generated-index', // 使用生成式索引页面 :contentReference[oaicite:5]{index=5}
                // title: 'API Reference',
                description: '自动生成的 API 文档总览',
                slug: '/api/classes', // 可选：自定义路径
                keywords: ['api', 'reference'],
            },
            items: typedocSidebar.items[0].items, // 插件生成的所有文档项
        },
        {
            type: 'category',
            label: 'Interfaces',
            link: {
                type: 'generated-index', // 使用生成式索引页面 :contentReference[oaicite:5]{index=5}
                // title: 'API Reference',
                description: '自动生成的 API 文档总览',
                slug: '/api/interfaces', // 可选：自定义路径
                keywords: ['api', 'reference'],
            },
            items: typedocSidebar.items[1].items, // 插件生成的所有文档项
        },
        {
            type: 'category',
            label: 'Type Aliases',
            link: {
                type: 'generated-index', // 使用生成式索引页面 :contentReference[oaicite:5]{index=5}
                // title: 'API Reference',
                description: '自动生成的 API 文档总览',
                slug: '/api/type_alias', // 可选：自定义路径
                keywords: ['api', 'reference'],
            },
            items: typedocSidebar.items[2].items, // 插件生成的所有文档项
        },
    ],
};

export default sidebars;
