import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
import typedocSidebar from './docs/api-core/typedoc-sidebar';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: 'tutorial'}],
  // api: [{type: 'autogenerated', dirName: 'api'}],
  apiSidebar: [
    // 1) 文档总览（index.md）
    {
      type: 'doc', // 文档链接项 :contentReference[oaicite:5]{index=5}
      id: 'api-core/index', // 文档 ID，对应 docs/api/index.md
      label: 'API Overview', // 在 sidebar 中显示的文字
    },
    // 2) 全局类型（globals.md）
    {
      type: 'doc',
      id: 'api-core/globals', // 对应 docs/api/globals.md
      label: 'Globals',
    },
    {
      type: 'category',
      label: 'Classes',
      link: {
        type: 'doc',
        id: 'api-core-classes-index',
      },
      items: typedocSidebar.items[0].items, // 插件生成的所有文档项
    },

    {
      type: 'category',
      label: 'Interfaces',
      link: {
        type: 'doc',
        id: 'api-core-interfaces-index',
      },
      items: typedocSidebar.items[1].items, // 插件生成的所有文档项
    },

    {
      type: 'category',
      label: 'Type Alias',
      link: {
        type: 'doc',
        id: 'api-core-type-aliases-index',
      },
      items: typedocSidebar.items[2].items, // 插件生成的所有文档项
    },
  ],
};

export default sidebars;
