name: Deploy test site to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Docusaurus repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Checkout SDK repo
        uses: actions/checkout@v3
        with:
          repository: webspatial/webspatial-sdk
          ref: c7b7aef7fa761d33c34d51d078cc5cb2882f8228
          path: XRSDK
          token: ${{ secrets.PAT_TOKEN }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9
          cache: "pnpm"

      - name: Run XRSDK setup
        working-directory: XRSDK
        run: npm run setup

      - name: Install Docusaurus dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Docusaurus site
        run: pnpm run build:test

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
