name: Manual Deploy to Org GitHub Pages

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy-to-org-pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Docusaurus repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9
          cache: "pnpm"

      - name: Install Docusaurus dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Docusaurus site
        run: pnpm run build

      - name: Deploy to Org GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          publish_repo: webspatial/webspatial.github.io
          publish_branch: main
          publish_dir: ./build
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
