name: CI/CD Docusaurus → GitHub Pages (SSH Deploy Key)

on:
  push:
    branches: [main]

permissions:
  contents: none # 主仓库不使用 GITHUB_TOKEN 做 git fetch

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1）加载 SSH 私钥（对应子模块仓库的 Deploy Key）
      - name: Checkout via SSH (repo + submodules)
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SUBMODULE_SSH_KEY }} # 私钥内容&#8203;:contentReference[oaicite:4]{index=4}
          ssh-known-hosts: github.com # 验证 host key
          submodules: recursive # 递归拉 submodule&#8203;:contentReference[oaicite:5]{index=5}
          persist-credentials: false # 禁用 HTTPS token 覆盖

      # 2）pnpm & 构建
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with: { run_install: false }

      - name: Setup Node.js (with pnpm cache)
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build site
        run: pnpm run build

      # 3）部署到 GitHub Pages
      - name: Deploy to Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages
